server:
  port: 9090
  
  
#actuators properties
  
management:  health:    circuitbreakers:      enabled: true
      
  endpoints:
    web:      exposure:        include: health,info,env,metrics
  endpoint:   health:      show-details: always
      
#resilience4j properties


resilience4j:  retry:    instances:      productService:
       max-retry-attempts: 5
       wait-duration: 10s
      
             
  
